# Generated by Django 2.0.7 on 2019-06-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('reason', models.CharField(choices=[('malware', 'Malware'), ('porn', 'Porn'), ('p2p', 'Pear-to-pear')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WhitelistedDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('reason', models.CharField(choices=[('mail', 'Mail'), ('productivity', 'Productivity')], max_length=32)),
            ],
        ),
    ]
